### ISSUE TITLE
Support for Django 2.x

### ISSUE THREAD

**Issue by marcolussetti** [mmcardle/django_builder#42]
I'm not sure I'd be able to provide a comprehensive list of changes, as I'm only now picking up 2.x but it does seem like there's a significant number of incompatibilities w/ 1.x

**Comment by mmcardle** [comment]
Hi @marcolussetti,
Thanks for your interest
This is something I would like to add but haven't had the time. Will hopefully get some time soon.

**Comment by haakenlid** [comment]
There's one major deprecation that should be taken into accunt to make this 2.0 compatible.

> The `on_delete` argument for `ForeignKey` and `OneToOneField` is now required in models and migrations. Consider squashing migrations so that you have fewer of them to update.

But this is a trivial fix, since `on_delete` has been around for a while, and it's highly recommended to include in your relation fields anyway.

You might also want to use the new url routing syntax, but I don't think it's mandatory.

**Comment by huochequan** [comment]
support 2.x will be great, thank you for your contribution.

**Comment by mmcardle** [comment]
This should be live now
